package com.my.instantmessag.mydb;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myDataDaoConfig;

    private final MyDataDao myDataDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myDataDaoConfig = daoConfigMap.get(MyDataDao.class).clone();
        myDataDaoConfig.initIdentityScope(type);

        myDataDao = new MyDataDao(myDataDaoConfig, this);

        registerDao(MyData.class, myDataDao);
    }
    
    public void clear() {
        myDataDaoConfig.getIdentityScope().clear();
    }

    public MyDataDao getMyDataDao() {
        return myDataDao;
    }

}
