package com.my.instantmessag.mydb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MY_DATA".
 */
public class MyData {

    private String user;    //当前登录的用户名
    private String name;    //联系人的用户名
    private String body;    //
    private String type;
    private String time;

    public MyData() {
    }

    public MyData(String name, String massage, String time) {
        this.name = name;
        this.body = massage;
        this.time = time;
    }

    public MyData(String user, String name, String body, String type, String time) {
        this.user = user;
        this.name = name;
        this.body = body;
        this.type = type;
        this.time = time;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

}
